// frontend/src/app/pages/battery/battery.component.ts
import { Component } from '@angular/core';
import { GuideData } from '../../models/guide.model';
import { GuidePageComponent } from '../guide/guide-page.component';

@Component({
  selector: 'app-battery-page',
  imports: [GuidePageComponent],
  templateUrl: './battery.component.html',
  styleUrl: './battery.component.css',
})
export class BatteryPageComponent {
  data: GuideData = {
  theme: 'orange',
  title: 'Coleta de Baterias e Pilhas: Guia Completo de Descarte',
  subtitle: '',
  intro: 'Baterias e pilhas contêm substâncias tóxicas e metais pesados que podem contaminar o meio ambiente quando descartados incorretamente. Veja como fazer o descarte adequado desses materiais:',
  colorLabel: 'LARANJA (em alguns sistemas)',
  colorText: 'Baterias e pilhas exigem coleta específica, não devendo ser misturadas com outros materiais. Procure pelo símbolo de "proibido descarte no lixo comum" nas embalagens.',
  listTitle: 'Tipos de baterias e pilhas',
  sections: [
    {
      title: 'Pilhas comuns:',
      items: ['Pilhas alcalinas (AA, AAA, C, D)', 'Pilhas de zinco-carbono', 'Pilhas recarregáveis de NiMH e NiCd', 'Pilhas botão (relógios, calculadoras)'],
    },
    {
      title: 'Baterias:',
      items: ['Baterias de celulares e smartphones', 'Baterias de notebooks e tablets', 'Baterias de câmeras digitais', 'Baterias de carros, motos e outros veículos', 'Baterias de no-breaks e sistemas de energia'],
    },
  ],
  stepsTitle: 'Como preparar pilhas e baterias para o descarte',
  steps: [
    { title: 'Isolamento', text: 'Coloque fita isolante nos terminais das baterias de lítio para evitar curto-circuito.' },
    { title: 'Armazenamento temporário', text: 'Guarde em recipientes secos, preferencialmente plásticos. Não misture com outros tipos de resíduos.' },
    { title: 'Integridade física', text: 'Nunca perfure, quebre ou desmonte pilhas e baterias. Evite contato com água ou umidade excessiva.' },
  ],
  cycleTitle: 'Processo de reciclagem de pilhas e baterias',
  cycleText: 'O processo de reciclagem envolve coleta, triagem, processamento mecânico, térmico e químico, neutralização e recuperação de materiais. Cada etapa é crucial para garantir a segurança e eficiência do processo.',
  benefitsTitle: 'Benefícios do descarte correto',
  benefits: [
    { icon: 'bi-tree', title: 'Ambientais', text: "Evita a contaminação do solo, lençóis freáticos e cursos d'água. Previne bioacumulação de metais pesados." },
    { icon: 'bi-cash', title: 'Econômicos', text: 'Recuperação de metais valiosos e desenvolvimento da indústria de reciclagem especializada.' },
  ],
  footerText: 'O descarte correto de pilhas e baterias é uma responsabilidade compartilhada entre consumidores, comerciantes e fabricantes.',
};
}

// recycle-connect-frontend/src/pages/Battery.jsx
import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import "../styles/pages/Battery.css";

const Battery = () => {
  return (
    <div className="battery-banner">
      <div className="hero-section">
        <Container>
          <h1>Coleta de Baterias e Pilhas: Guia Completo de Descarte</h1>
          <p className="subtitle">
            Baterias e pilhas contêm substâncias tóxicas e metais pesados que podem contaminar o meio ambiente quando descartados incorretamente. Veja como fazer o descarte adequado desses materiais:
          </p>
        </Container>
      </div>

      <Container>
        <h2 className="section-title">Identificação e Separação</h2>
        <Row>
          <Col lg={8} className="mx-auto">
            <p className="lead">
              Cor da categoria: <strong>LARANJA</strong> (em alguns sistemas)
            </p>
            <p>
              Baterias e pilhas exigem coleta específica, não devendo ser misturadas com outros materiais. Procure pelo símbolo de "proibido descarte no lixo comum" nas embalagens.
            </p>
          </Col>
        </Row>

        <h2 className="section-title">Tipos de baterias e pilhas</h2>
        <Row>
          <Col md={6}>
            <div className="recycle-list">
              <h4>Pilhas comuns:</h4>
              <ul>
                <li>Pilhas alcalinas (AA, AAA, C, D)</li>
                <li>Pilhas de zinco-carbono</li>
                <li>Pilhas recarregáveis de NiMH e NiCd</li>
                <li>Pilhas botão (relógios, calculadoras)</li>
              </ul>
            </div>
          </Col>
          <Col md={6}>
            <div className="recycle-list">
              <h4>Baterias:</h4>
              <ul>
                <li>Baterias de celulares e smartphones</li>
                <li>Baterias de notebooks e tablets</li>
                <li>Baterias de câmeras digitais</li>
                <li>Baterias de carros, motos e outros veículos</li>
                <li>Baterias de no-breaks e sistemas de energia</li>
              </ul>
            </div>
          </Col>
        </Row>

        <h2 className="section-title">Como preparar pilhas e baterias para o descarte</h2>
        <div className="steps-container">
          {[
            { id: 1, number: 1, title: "Isolamento", text: "Coloque fita isolante nos terminais das baterias de lítio para evitar curto-circuito." },
            { id: 2, number: 2, title: "Armazenamento temporário", text: "Guarde em recipientes secos, preferencialmente plásticos. Não misture com outros tipos de resíduos." },
            { id: 3, number: 3, title: "Integridade física", text: "Nunca perfure, quebre ou desmonte pilhas e baterias. Evite contato com água ou umidade excessiva." }
          ].map((step) => (
            <div key={step.id} className="step d-flex">
              <div className="step-number">{step.number}</div>
              <div className="step-content">
                <h4>{step.title}</h4>
                <p>{step.text}</p>
              </div>
            </div>
          ))}
        </div>

        <h2 className="section-title">Processo de reciclagem de pilhas e baterias</h2>
        <Row>
          <Col lg={8} className="mx-auto">
            <p>
              O processo de reciclagem envolve coleta, triagem, processamento mecânico, térmico e químico, neutralização e recuperação de materiais. Cada etapa é crucial para garantir a segurança e eficiência do processo.
            </p>
          </Col>
        </Row>

        <h2 className="section-title">Benefícios do descarte correto</h2>
        <Row>
          <Col md={6}>
            <div className="benefit-card">
              <i className="bi bi-tree"></i>
              <h4>Ambientais</h4>
              <p>Evita a contaminação do solo, lençóis freáticos e cursos d'água. Previne bioacumulação de metais pesados.</p>
            </div>
          </Col>
          <Col md={6}>
            <div className="benefit-card">
              <i className="bi bi-cash"></i>
              <h4>Econômicos</h4>
              <p>Recuperação de metais valiosos e desenvolvimento da indústria de reciclagem especializada.</p>
            </div>
          </Col>
        </Row>
      </Container>

      <div className="footer">
        <Container>
          <p>O descarte correto de pilhas e baterias é uma responsabilidade compartilhada entre consumidores, comerciantes e fabricantes.</p>
        </Container>
      </div>
    </div>
  );
};

export default Battery;
