// frontend/src/app/pages/metal/metal.component.ts
import { Component } from '@angular/core';
import { GuideData } from '../../models/guide.model';
import { GuidePageComponent } from '../guide/guide-page.component';

@Component({
  selector: 'app-metal-page',
  imports: [GuidePageComponent],
  templateUrl: './metal.component.html',
  styleUrl: './metal.component.css',
})
export class MetalPageComponent {
  data: GuideData = {
  theme: '#ffd723',
  title: 'Coleta de Metal: Guia Completo de Reciclagem',
  subtitle: '',
  intro: 'A reciclagem de metais é um dos processos mais eficientes e economicamente viáveis dentro da cadeia de reciclagem. Confira como fazer a coleta seletiva de metais corretamente:',
  colorLabel: 'AMARELO',
  colorText: 'Todos os tipos de metal devem ser descartados em lixeiras amarelas. Os metais geralmente são identificados pelos símbolos 40 a 49 dentro do triângulo de reciclagem.',
  listTitle: 'Tipos de metais recicláveis',
  sections: [
    {
      title: 'Metais ferrosos:',
      items: ['Latas de alimentos em conserva', 'Tampas metálicas de garrafas', 'Panelas e utensílios de cozinha de ferro', 'Clipes, grampos e pregos', 'Ferramentas de ferro', 'Aço em geral'],
    },
    {
      title: 'Metais não-ferrosos:',
      items: ['Latas de alumínio (refrigerantes e cervejas)', 'Papel alumínio limpo', 'Embalagens metalizadas de alimentos', 'Fios e cabos de cobre', 'Peças de bronze e latão', 'Esquadrias de alumínio'],
    },
  ],
  stepsTitle: 'Como preparar o metal para reciclagem',
  steps: [
    { title: 'Limpeza básica', text: 'Enxágue para remover resíduos de alimentos. Retire rótulos de papel quando possível.' },
    { title: 'Compactação', text: 'Amasse latas para reduzir volume. Separe tampas metálicas dos recipientes de vidro.' },
    { title: 'Separação magnética (opcional)', text: 'Use um ímã para separar metais ferrosos (que grudam) dos não-ferrosos (que não grudam).' },
  ],
  cycleTitle: 'Ciclo de reciclagem do metal',
  cycleText: 'O ciclo de reciclagem do metal envolve coleta, triagem, limpeza, trituração, fusão, solidificação e fabricação. Cada etapa é crucial para transformar o metal usado em novos produtos.',
  benefitsTitle: 'Benefícios da reciclagem de metal',
  benefits: [
    { icon: 'bi-tree', title: 'Ambientais', text: 'Reduz a extração de minérios e economiza energia. Diminui a emissão de gases do efeito estufa.' },
    { icon: 'bi-cash', title: 'Econômicos', text: 'Alto valor no mercado de reciclagem. Gera renda para catadores e cooperativas.' },
  ],
  footerText: 'A reciclagem de metais é um exemplo de sucesso na economia circular, combinando benefícios ambientais com vantagens econômicas significativas.',
};
}

// recycle-connect-frontend/src/pages/Metal.jsx
import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import "../styles/pages/Metal.css";

const Metal = () => {
  return (
    <div className="metal-banner">
      <div className="hero-section">
        <Container>
          <h1>Coleta de Metal: Guia Completo de Reciclagem</h1>
          <p className="subtitle">
            A reciclagem de metais é um dos processos mais eficientes e economicamente viáveis dentro da cadeia de reciclagem. Confira como fazer a coleta seletiva de metais corretamente:
          </p>
        </Container>
      </div>

      <Container>
        <h2 className="section-title">Identificação e Separação</h2>
        <Row>
          <Col lg={8} className="mx-auto">
            <p className="lead">
              Cor da categoria: <strong>AMARELO</strong>
            </p>
            <p>
              Todos os tipos de metal devem ser descartados em lixeiras amarelas. Os metais geralmente são identificados pelos símbolos 40 a 49 dentro do triângulo de reciclagem.
            </p>
          </Col>
        </Row>

        <h2 className="section-title">Tipos de metais recicláveis</h2>
        <Row>
          <Col md={6}>
            <div className="recycle-list">
              <h4>Metais ferrosos:</h4>
              <ul>
                <li>Latas de alimentos em conserva</li>
                <li>Tampas metálicas de garrafas</li>
                <li>Panelas e utensílios de cozinha de ferro</li>
                <li>Clipes, grampos e pregos</li>
                <li>Ferramentas de ferro</li>
                <li>Aço em geral</li>
              </ul>
            </div>
          </Col>
          <Col md={6}>
            <div className="recycle-list">
              <h4>Metais não-ferrosos:</h4>
              <ul>
                <li>Latas de alumínio (refrigerantes e cervejas)</li>
                <li>Papel alumínio limpo</li>
                <li>Embalagens metalizadas de alimentos</li>
                <li>Fios e cabos de cobre</li>
                <li>Peças de bronze e latão</li>
                <li>Esquadrias de alumínio</li>
              </ul>
            </div>
          </Col>
        </Row>

        <h2 className="section-title">Como preparar o metal para reciclagem</h2>
        <div className="steps-container">
          {[
            { id: 1, number: 1, title: "Limpeza básica", text: "Enxágue para remover resíduos de alimentos. Retire rótulos de papel quando possível." },
            { id: 2, number: 2, title: "Compactação", text: "Amasse latas para reduzir volume. Separe tampas metálicas dos recipientes de vidro." },
            { id: 3, number: 3, title: "Separação magnética (opcional)", text: "Use um ímã para separar metais ferrosos (que grudam) dos não-ferrosos (que não grudam)." }
          ].map((step) => (
            <div key={step.id} className="step d-flex">
              <div className="step-number">{step.number}</div>
              <div className="step-content">
                <h4>{step.title}</h4>
                <p>{step.text}</p>
              </div>
            </div>
          ))}
        </div>

        <h2 className="section-title">Ciclo de reciclagem do metal</h2>
        <Row>
          <Col lg={8} className="mx-auto">
            <p>
              O ciclo de reciclagem do metal envolve coleta, triagem, limpeza, trituração, fusão, solidificação e fabricação. Cada etapa é crucial para transformar o metal usado em novos produtos.
            </p>
          </Col>
        </Row>

        <h2 className="section-title">Benefícios da reciclagem de metal</h2>
        <Row>
          <Col md={6}>
            <div className="benefit-card">
              <i className="bi bi-tree"></i>
              <h4>Ambientais</h4>
              <p>Reduz a extração de minérios e economiza energia. Diminui a emissão de gases do efeito estufa.</p>
            </div>
          </Col>
          <Col md={6}>
            <div className="benefit-card">
              <i className="bi bi-cash"></i>
              <h4>Econômicos</h4>
              <p>Alto valor no mercado de reciclagem. Gera renda para catadores e cooperativas.</p>
            </div>
          </Col>
        </Row>
      </Container>

      <div className="footer">
        <Container>
          <p>A reciclagem de metais é um exemplo de sucesso na economia circular, combinando benefícios ambientais com vantagens econômicas significativas.</p>
        </Container>
      </div>
    </div>
  );
};

export default Metal;
